version: "3.9"
services: 
  mongo:
    image: mongo:latest
    container_name: mongoDB
    ports: 
       - "27017:27017"
    environment:
       MONGO_INITDB_ROOT_USERNAME: Admin
       MONGO_INITDB_ROOT_PASSWORD: "Admin@1234"  
